name: date_time_popover_picker
description: Popover Widget to select/set DateTime
version: 0.0.1+9
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.14.0 <3.0.0" #Dart SDK 4-SEP-2021
  flutter: ">=2.5.0"

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_classes:
    git:
      url: https://github.com/GitHubStuff/flutter_classes.git
  flutter_modular: ^3.4.1+1
  intl: ^0.17.0
  popover: ^0.2.6+2
  theme_manager:
    git:
      url: https://github.com/GitHubStuff/theme_manager.git

dev_dependencies:
  test: ^1.17.12

flutter:
  uses-material-design: true
